#!/usr/bin/python3
def raise_exception_msg(message="the name is not found"):
    raise NameError(message)

